name: Build Release

on: push

jobs:
  build:
    name: "Build Release"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: macos-latest
            release_suffix: mac
          - os: windows-latest
            release_suffix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Linux Build
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'
        run: npm ci && npm run make
        if: matrix.os == 'ubuntu-latest'

      - name: Run Windows Build
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'
        run: npm ci && npm run make
        if: matrix.os == 'windows-latest'

      - name: Run macos Build
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'
        run: npm ci && npm run make
        if: matrix.os == 'macos-latest'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /out
        if: startsWith(github.ref, 'refs/tags/')