name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false
  build:
    name: "Build Release"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: macos-latest
            release_suffix: mac
          - os: windows-latest
            release_suffix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Linux Build
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'
        run: npm ci && npm run make
        if: matrix.os == 'ubuntu-latest'

      - name: Run Windows Build
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'
        run: npm ci && npm run make
        if: matrix.os == 'windows-latest'

      - name: Run macos Build
        uses: actions/setup-node@v3
        with:
          node-version: 'lts'
        run: npm ci && npm run make
        if: matrix.os == 'macos-latest'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: /out

        